/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MyfamilyFamilyIdRouteImport } from './routes/myfamily/$familyId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MyfamilyFamilyIdRoute = MyfamilyFamilyIdRouteImport.update({
  id: '/myfamily/$familyId',
  path: '/myfamily/$familyId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/myfamily/$familyId': typeof MyfamilyFamilyIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/myfamily/$familyId': typeof MyfamilyFamilyIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/myfamily/$familyId': typeof MyfamilyFamilyIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/myfamily/$familyId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/myfamily/$familyId'
  id: '__root__' | '/' | '/myfamily/$familyId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MyfamilyFamilyIdRoute: typeof MyfamilyFamilyIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/myfamily/$familyId': {
      id: '/myfamily/$familyId'
      path: '/myfamily/$familyId'
      fullPath: '/myfamily/$familyId'
      preLoaderRoute: typeof MyfamilyFamilyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MyfamilyFamilyIdRoute: MyfamilyFamilyIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
